#functions that have to do with managing the files generated by this program

import subprocess

def cleanExcess(numberOfPages):
   i = 0
   while i<numberOfPages:
     subprocess.call('rm page_' + str(i+1) + '.jpg', shell=True) #removes image of pdf
     subprocess.call('rm page_' + str(i+1) + '.txt', shell=True) #removes txt file of text from image of pdf generated through tesseract
     i = i + 1 
